---
title: "data import"
author: "Keyi Wang"
date: "9/22/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(haven)
```
```{r}
litters_data1 = read_csv(file = "./data/FAS_litters.csv")
litters_data2 = read_csv(
  file = "./data/FAS_litters.csv", skip = 10, col_names = FALSE)
### converting name from capital letters into lower case 
litters_data = janitor::clean_names(litters_data1)
pups_data1 = read_csv(file = "./data/FAS_pups.csv")
```
```{r}
##play with column names
litters_data5 = read_csv(file = "./data/FAS_litters.csv",
                         col_types = cols(
                            `Group` = col_character(),
                            `Litter Number` = col_character(),
                            `GD0 weight` = col_double(),
                            `GD18 weight` = col_double(),
                            `GD of Birth` = col_integer(),
                            `Pups born alive` = col_integer(),
                            `Pups dead @ birth` = col_integer(),
                            `Pups survive` = col_integer()
                           
                         )
                         )
##short hand version to change column types
litters_data4 = read_csv(file = "./data/FAS_litters.csv",
  col_types = "ccddiiii"
)

### changing specification for data pups
pups_data2 = read_csv(file = "./data/FAS_pups.csv",
                      col_types = "ciiiii"
                      )

```
### insted of export file from xl into csv, use readxl function
```{r}
mlb11_data_subset = read_excel(path = "./data/mlb11.xlsx",
                        range = "A1:D7"
                      )
### export csv data 
write_csv(mlb11_data_subset, path = "./data/mlb11.xlsx")
```

## read in SAS
```{r}
pulse_data = read_sas("./data/public_pulse_data.sas7bdat")
```



